name: Update Subscription

on:
  workflow_dispatch:

jobs:
  update-subscription:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Git user
      run: |
        git config --global user.name "AlvisDroy"
        git config --global user.email "alvis593088386@gmail.com"

    - name: Pull latest changes
      run: git pull origin main --rebase

    - name: Fetch and update subscriptions
      run: |
        curl -o nodes_1.txt "https://sub.kaiche.tk/?token=auto"
        curl -o nodes_2.txt "https://raw.githubusercontent.com/ripaojiedian/freenode/main/clash"
        cat nodes_1.txt nodes_2.txt > all_nodes.txt
        git add nodes_1.txt nodes_2.txt all_nodes.txt
        git commit -m "Update subscription nodes"

    - name: Push changes
      run: git push origin main
