name: Update Subscription
on:
  schedule:
    - cron: '0 0 * * *'  # 这个 cron 表达式代表每天0点运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  update-subscription:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # 确保使用最新版本

    - name: Set up Git user information
      run: |
        git config --global user.name "AlvisDroy"
        git config --global user.email "alvis593088386@gmail.com"

    - name: Ensure clean working directory
      run: |
        git status
        git reset --hard
        git clean -fdx

    - name: Fetch subscriptions
      run: |
        curl -o nodes_1.txt "https://sub.kaiche.tk/?token=auto"
        curl -o nodes_2.txt "https://raw.githubusercontent.com/ripaojiedian/freenode/main/clash"
        cat nodes_1.txt nodes_2.txt > all_nodes.txt

    - name: Commit changes
      run: |
        git add nodes_1.txt nodes_2.txt all_nodes.txt
        git commit -m "Update subscription nodes"

    - name: Debugging
      run: |
        echo "Current directory status:"
        git status
        echo "Current branch:"
        git branch -a
        echo "Last commit:"
        git log -1

    - name: Push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git push
